### ISSUE TITLE
My templates are not transformed

### ISSUE THREAD

**Issue by weitzhandler** [olegsych/T4Toolbox#15]
Hi,

Please refer to my issue on [StackOverflow](http://stackoverflow.com/q/31563575/75500).

In general, I can't find the `Custom Tool` property on the `tt` file, in VS 2015 RTM, in an ASP.NET 5 (vNext) project.

**Comment by ghost** [comment]
Running a quick test from the details that are available (you haven't specified project type) ... I did not see a way to even add a T4 file (either raw.tt or T4Toolbox template). I chose "Web Application" and "MVC" for a quick test. When I want to add a new file to the ASP.NET MVC WebApp project, I'm prompted for "server-side" or "client-side" file types, and I didn't see Text Template in either of those sub-categories, off-hand.

I don't believe "Run Custom Tool" is a part of T4 Toolbox. And T4Toolbox is definitely NOT ASP.NET. They're two different things (T4Toolbox can be complimentary). For good measure, I disabled T4Toobox, restarted VS, created a new.tt file, and "Run Custom Tool" was available. (It's part of transforming text templates.)

On the other hand, if I add a class library to a test project (MVC WebApp), reference the library, build the project, the class generated by the .tt file becomes available to the WebApp project when I import the library... 

```
using TestLib;
namespace whatever {
    class RunTest {
        public RunTest() {
            Debug.Assert(TestLib.IsWorking, true);
        }
    }
}
```

Hopefully this helps.

In addition, you can use DTE to do things like get references to other projects, scan & generate tt files based off of project settings & contents, inject files into projects, etc... (_a little more advanced than a basic tt file, or T4Toolbox's intended usage -- Oleg can correct me on this if I'm wrong_).

**Comment by weitzhandler** [comment]
@MudaKaizen I just added the `tt` file as plain text renaming the `tt` extension.
So you say they **disabled** T4 in ASP.NET projects?

**Comment by ghost** [comment]
@weitzhandler 

No, I'm saying that I disabled my T4Toolbox to (double) check that "Run Custom Tool" isn't a specific part of T4Toolbox. (_It's a general tool applying to VS Projects that DO SUPPORT Text Templating._)

As far as T4 files in ASP.NET projects -- I've never done things this way. I always run my T4 files in separate class libraries. (_I don't know if T4 support was removed from ASP.NET 5 projects. Other answers on your StackOverflow post point to this. If there was once support, then, yes, it's been removed, at least temporarily during development / beta._)

**Here's some helpful food-for-thought (_the internals of how this T4 file works are super-helpful for understanding injection of generated files into other projects in a solution, at least as a basis to go off of_):**
[Multiple Outputs From T4 Made Easy (Revisited)](http://damieng.com/blog/2009/11/06/multiple-outputs-from-t4-made-easy-revisited)
[Code](https://github.com/damieng/DamienGKit/tree/master/T4/MultipleOutputHelper)

**From Oleg**:
[How to generate multiple outputs from single T4 template](http://www.olegsych.com/2008/03/how-to-generate-multiple-outputs-from-single-t4-template/)
[T4 Tutorial: Creating complex code generators](http://www.olegsych.com/2008/09/t4-tutorial-creating-complex-code-generators/)
(_just on the latter basis alone, better to separate into class libraries_)

**Tangible T4 Editor**:
[How to generate multiple output files from a single T4 Template](http://t4-editor.tangible-engineering.com/blog/how-to-generate-multiple-output-files-from-a-single-t4-template.html)

While "multiple outputs" doesn't address your specific situation, again, learning from these helped me understand how to target other projects in a solution (_along with learning DTE to target projects & solutions_).

That's my recommendation: A separate class library for T4 files. It's a semantic separation of concerns type-of-thing. But, I completely understand your want & intent to provide generated config files directly in your base projects -- though this falls in the category / domain of tool-chain, and, you should have separate tools to manage this, IMO.

**Comment by olegsych** [comment]
@MudaKaizen is right, the _Custom Tool_ feature is provided by the classic C# and VB project system. ASP.NET 5 projects use a completely new project system, which doesn't appear to support it. I would suggest submitting this as a bug on [Visual Studio Connect](http://connect.microsoft.com/VisualStudio) first, perhaps with enough votes the VS platform team will agree to implement it. If that doesn't happen, we may be able to implement this feature in T4 Toolbox.
