### ISSUE TITLE
How to work with different Path/File creation

### ISSUE THREAD

**Issue by Intelli-Soft** [olegsych/T4Toolbox#17]
I have read your post of how Files can be outputted in different Folders. - But I can't get it working with my Template.
The first Thing is, that I have to Inherit from Template. - But I use Inheritance within my Code template. - So there would be double inheritance, what isn't supported.

 I have a "complex" .tt file (which is working) - But I am not able to transform it.
 So, I hope someone can help me.
 I attach my .tt file. The result of this .tt file should be generated somewhere else.
 THX a lot - Have a nice day

<#@ template debug="true" hostspecific="true" language="VB" #>
<#@ include file="T4Toolbox.tt" #>
<#@ output extension=".vb" #>
<#@ assembly name="System.Windows.Forms" #>

<#@ import namespace="System.Resources" #>
<#@ import namespace="System.Collections" #>
<#@ import namespace="System.IO" #>
<#@ import namespace="System.ComponentModel.Design" #>

<#

```
Dim myNameSpace As String = "UI"
Dim myClassName As String = "GetCustomerUI"
Dim myTypeOfResourceManager As String = "TypeOfResourceManager.UICustomer"
Dim myResourcePath As String = "Resources\de-AT\Customer"

Dim myFileName As String = "Customer.de-AT.resx"
Dim myFilePath As String = Path.Combine(Path.GetDirectoryName(Me.Host.ResolvePath("")), myResourcePath, myFileName)
Dim myReader= New ResXResourceReader(myFilePath)

myreader.UseResXDataNodes = true
```
# >

namespace <#=myNameSpace #>
  Public Class <#=myClassName #>
        Inherits Localize.Localization
        Public Sub New()
            MyBase.New(<#= myTypeOfResourceManager #>)
        End Sub
<#   For each item As DictionaryEntry In myReader 
        Dim name = item.Key
        Dim node = DirectCast(item.Value, ResXDataNode)
        Dim comment = node.Comment
        Dim summary As String = String.Empty
        If Not [String].IsNullOrEmpty(comment) Then
            summary += " - " + comment
        End If
# >

```
    ''' <summary>
    ''' <#= summary #>
    ''' </summary>
    ''' <remarks></remarks>

    Public ReadOnly Property Get<#= name #> As String
        Get
            Return MyBase.GetLocalizedString("<#= name #>")
        End Get
    End Property
```

<#
    Next
# >

```
End Class
```

End NameSpace

**Comment by olegsych** [comment]
You might want to start with a _simple_ template to figure this out. First you need to wrap your raw T4 template into a T4 Toolbox `Template` as described [here](http://www.olegsych.com/2008/09/t4-tutorial-creating-reusable-code-generation-templates/). Then you can set `Template.Output.File` and `Template.Output.Directory` properties to control where the generated output will be saved as described [here](http://www.olegsych.com/2010/03/t4-tutorial-integrating-generated-files-in-visual-studio-projects/). Refer to doc comments in [OutputItem.cs](https://github.com/olegsych/T4Toolbox/blob/master/src/T4Toolbox/OutputItem.cs) for details. 

P.S. The articles haven't been updated in a while. I hope to eventually move them to [GitHub Pages](http://olegsych.github.io/T4Toolbox/getting-started.html) and looking for volunteers who can help with that.

**Comment by Intelli-Soft** [comment]
Hey Oleg
Thx for your answer. - First of all, the link, where the T4 Template should be descriebed, isn't working.
But I have read your Posts and I (think) I understood the Transformation with a "simple" class.
But as I said above, I use Inherits within my Code and I can't Inherit two classes. - This is, where I don't got the Clou how to solve this.

THX - And have a nice weekend

**Comment by olegsych** [comment]
I've fixed the link in my previous comment; sorry about that copy & paste error. Please help to understand the problem you are experiencing by providing 
- a minimal repro, without code specific to your application
- a specific, detailed description of the problem, including transformation errors, build errors, etc
- a list of attempted solutions and their outcomes
