### ISSUE TITLE
Query which version of T4 Toolbox

### ISSUE THREAD

**Issue by mwpowellhtx** [olegsych/T4Toolbox#20]
I would like to query the version of T4 Toolbox used to generate source code. It's simple enough to embed boilerplate comments like, _this code is auto-generated by ..._, this sort of thing. But it would be that much more useful to determine the actual version of the underlying T4 Toolbox as one more point of traceability during maintenance cycles. Perhaps this is something which may be exposed via the `this` that's available, or if there are extensions for this, etc. Thanks...

**Comment by olegsych** [comment]
You can use version of the T4Toolbox assembly. Off the top of my head, something like this should work:

``` C#
typeof(T4Toolbox.Template).Assembly.GetName().Version
```

I know that .NET code generators include code generator version in autogenerated comments by convention, but I've always found this to be an annoyance. How would this be useful in your scenarios?

**Comment by mwpowellhtx** [comment]
I want to save timestamp and version numbers as a matter of commented documentation, i.e. generated by such and such a version and when.

**Comment by mwpowellhtx** [comment]
It sounds like a stupid question, but where do I find that reference? Assuming I must reference `T4Toolbox.VisualStudio`, then add namespace `T4Toolbox`, and/or use the full name `T4Toolbox.Template`? Yes? I have the VS2013 extension installed to facilitate my T4 text transformations.

**Comment by mwpowellhtx** [comment]
With a little digging on my part, can I count on the `HKCU\Software\Microsoft\VisualStudio\12.0\ExtensionManager\EnabledExtensions` Registry key and `T4Toolbox.12,12.10.1.41` value <sup>[1]</sup> to be there, in order to derive the installed `T4Toolbox.dll` assembly location? In my case, for example, that gets installed in `C:\Users\<User/>\AppData\Local\Microsoft\VisualStudio\12.0\Extensions\<RandomDir/>\`, but I gather this would vary from user to user supporting the code generation and build process(es).

That you know of, is there a simpler way to derive the T4Toolbox assembly reference?

Reference:

<sup>1</sup> [What is in T4 Toolbox](http://www.olegsych.com/2008/12/what-is-in-t4-toolbox/)

Thanks...

**Comment by mwpowellhtx** [comment]
Well, it's not terrible, I just wonder if it could be simpler.

``` C#
    private static Assembly GetToolboxAssembly()
    {
        var toolboxPath = Path.Combine(GetToolPath(), "T4Toolbox.dll");
        return Assembly.LoadFile(toolboxPath);
    }

    private static string GetToolPath()
    {
        const string path = @"Software\Microsoft\VisualStudio\12.0\ExtensionManager\EnabledExtensions";
        using (var key = Registry.CurrentUser.OpenSubKey(path))
        {
            const string value = @"T4Toolbox.12,12.10.1.41";
            // ReSharper disable once PossibleNullReferenceException
            return (string) key.GetValue(value, string.Empty);
        }
    }
```

With generated output:

``` C#
// Generated by a {T4Toolbox, Version=12.0.0.0, Culture=neutral, PublicKeyToken=dc4a538672a7b38f} script on 2015-11-05T22:44:15.9189647Z local 2015-11-05T17:44:15.9199648-05:00.
```
