### ISSUE TITLE
Wrong completion after <#= ... #

### ISSUE THREAD

**Issue by jho1965us** [olegsych/T4Toolbox#21]
should be  #>

(apparently newlines in text between <#= and #> is erased before compilation so any preprocessor directive will be illegal)

![image](https://cloud.githubusercontent.com/assets/4348979/10994750/9735d31c-8478-11e5-8ee7-01ab55df93b1.png)

**Comment by olegsych** [comment]
T4 Toolbox editor extension does not provide C# completion lists today. Do you have any other extensions that may be doing this? What is the extension of this template file?

**Comment by jho1965us** [comment]
Sorry my mistake this was supposed to go to ForFea
