### ISSUE TITLE
'T4Toolbox.OutputItem' does not contain a definition for 'BuildAction' &  'BuildProperties' 

### ISSUE THREAD

**Issue by jhermoso** [olegsych/T4Toolbox#22]
Hi,
I'm migrating some templates from vs2010 to vs 2015 but now I get some errors when I try to use the old OutputInfo properties BuildAction and BuildProperties. Can you suggest me a workaround to get this function? 
Thanks 
Javier

**Comment by olegsych** [comment]
In T4Toolbox for VS 2015, the `BuildAction` property (named consistently with the Visual Studio UX terminology) was replaced with the `ItemType` property (named consistently with the MSBuild terminology). You can set it to any `string` or use the constants defined in the `ItemType` class, such as the `ItemType.Compile` or `ItemType.Content`. Similarly, the `BuildProperties` was replaced by the `Metadata` property. For complete details, see the [OutputItem](https://github.com/olegsych/T4Toolbox/blob/master/src/T4Toolbox/OutputItem.cs) class definition.
