### ISSUE TITLE
 system.runtime.remoting.remotingexception

### ISSUE THREAD

**Issue by ybadragon** [olegsych/T4Toolbox#23]
I receive this error when running my t4 against a database, which pulls in stored procedures and gets information on the parameters of that stored procedure. I then use this information to create services.

I know I'm not receiving the error due to an issue on my end as this only happens on long running t4 generation instances. It happens after ~5 minutes. As I said, if I run it on a smaller list of stored procedures, it is running correctly.

Any idea what would cause this, and a potential work-around?

**Comment by olegsych** [comment]
It's hard to tell without [debugging](https://msdn.microsoft.com/en-us/library/bb126247.aspx) your template. Does your template use T4 Toolbox? Does it transform at design time or built-time?

**Comment by ybadragon** [comment]
We were able to get around the issue by splitting the creator into multiple creators and running them individually. It transforms at build time. Actually it only transforms when we right click and say run custom tool. It was an issue with a timeout, but it wasn't a server timeout, it was specific to .NET.
