### ISSUE TITLE
Issue with encoding

### ISSUE THREAD

**Issue by dlaptin** [olegsych/T4Toolbox#28]
In my project T4Toolbox.ScriptFileGenerator is used to generate js resources from the *.resx files.

The encoding is specified using the output directive:
<#@ output extension=".js" encoding="utf-16" #>

There is the copyright symbol '©' in the template which fails to encode if the whole solution being built,  please see the screenshot:

Also there is a warning while opening this file with the KDiff.

But transformation is fine if the single web project is being built.

Are there any differences in how transformations are performed while building a solution and building a single project?

**Comment by dlaptin-softheme** [comment]
Should I provide any additional info?
