### ISSUE TITLE
Missing T4 Toolbox in New Project

### ISSUE THREAD

**Issue by khoait** [olegsych/T4Toolbox#33]
Hello,

I am using VS2015 Community. After installing T4 Toolbox extension, and restarted VS, I cannot find the T4 Toolbox section in New Project.

Please help.

**Comment by oceanho** [comment]
I am using VS Enterprise 2015 Update 3. I can find the T4 Toolbox at VS Help window,but i cannot find The T4 Toolbox section in New Project.
@olegsych. please help.thanks

**Comment by kenny-evitt** [comment]
I'm pretty sure the "T4 Toolbox" section is only in the *New **File*** menu/window *in an existing project*.

**Comment by olegsych** [comment]
Thanks, @kenny-evitt! That's right, T4 Toolbox adds only _item_ templates for C# and VB projects.
