### ISSUE TITLE
Links to old content please  - Output in multiple Files

### ISSUE THREAD

**Issue by walcher** [olegsych/T4Toolbox#38]
Do you have the links to the tutorials where you show how to get multiple files?

i have been cheking for it on internet but the link is broken.

http://olegsych.com/2008/09/t4-tutorial-creating-complex-code-generators/

Thanks

**Comment by kenny-evitt** [comment]
See the older issue #29 – I commented with links to (archived versions) of the old blog posts and I also included some examples of my own based on those posts (and my limited experience generating multiple output files).

**Comment by olegsych** [comment]
@kenny-evitt thanks for responding.
