### ISSUE TITLE
Failed to load T4ToolBox assembly

### ISSUE THREAD

**Issue by Maximushep** [olegsych/T4Toolbox#6]
However after installing the latest edition 12.10.1.27, I get the error "could not load file or assembly 'T4Toolbox Version=12.0.0.0...."

I am using this on vs2013 with .NET 4.5.2?

It was working earlier and I had to reinstall studio, after which when I installed the new extension, it does not work.

Did I miss something on my configurations?

Configuration:
VS 2013 Premium
.NET 4.5, 4.5.1, 4.5.2 (4 is not installed).
EF 6.1, etc.

**Comment by AGeekDad** [comment]
I'm having the same issue. The previous version was working fine, but I'm getting the same error with version 12.10.1.27.

**Comment by Maximushep** [comment]
Where do we find the prior version, I am stuck till then or Oleg, is this a quick fix?

**Comment by Assam** [comment]
I am also facing similar problem have also raised separate issue with error message. Oleg would appreciate if you could point to previous version of the extension. Btw in my team we have all kinds of Visual Studio flavours i.e. Ultimate, Premium, Proffesional etc and we all seem to be stuck with the same problem.

**Comment by olegsych** [comment]
Thanks a quick reaction, everyone. I uploaded the original v12.10.0.0 to the Visual Studio gallery, so if you are blocked, you should be able to uninstall v12.10.1.27 and reinstall the previous version using the Extension Manager in Visual Studio. 

Before you do that, I'd appreciate a bit of help to understand why this is occurring in your environment and not in mine. 
- Which update of Visual Studio 2013 are you running? 
- Did you have the previous version of the T4 Toolbox installed?
- Do you have Visual Studio 2015 installed?
- Can you make a _minimal_ template that repro the problem?

Can you also try deleting the MEF cache from your environment and see if v12.10.1.27 starts working?

```
rmdir %LOCALAPPDATA%\Microsoft\VisualStudio\12.0\ComponentModelCache /s /q
```

**Comment by olegsych** [comment]
By the way, the only thing I can think of that might cause this was removal of the strong name signing from the `T4Toolbox.dll`. I was moving the code from a private repository on VisualStudio.com to GitHub and decided to drop strong naming because I didn't want to do the extra work to make the key secure (see #4). I'd appreciate your thoughts on this.

**Comment by Assam** [comment]
hi Oleg,
Thanks for the continued good work. Please find my response below
Which update of Visual Studio 2013 are you running?
update 4
Did you have the previous version of the T4 Toolbox installed?
yes
Do you have Visual Studio 2015 installed?
no
Can you make a minimal template that repro the problem?
currently in office but can do that later on. For this can you please guide me in how to create the template you are looking for.
rmdir %LOCALAPPDATA%\Microsoft\VisualStudio\12.0\ComponentModelCache /s /q
already tried last night but didn't work
I think it might got to do with public assembly for previous version to private assembly. Perhaps it needs some kind of assembly redirection. Only guessing!!
Regards.
Assam.

**Comment by Assam** [comment]
Ok it seems that older version is working fine. Such a relief. Btw if you install v12.10.1.27 on a fresh machine then you would very easily see the issue first hand.

**Comment by Maximushep** [comment]
Thanks Oleg, the 12.10 version I installed and it is back to working.
Once new version is available, will update to that.

Thanks again for all your work on T4 toolbox.

**Comment by olegsych** [comment]
It sounds like we need to go back to strong-naming the T4Toolbox assemblies (#5). Thanks, everyone.
